package rules

import com.model.Product

rule "Offer for Diamond"
	when 
		productObject: Product(type=="diamond")
	then
		productObject.setDiscount(15);
		System.out.println("Total discount is:"+productObject.getDiscount());
	end
	
	
rule "Offer for Gold"
	when 
		productObject: Product(type=="gold")
	then
		productObject.setDiscount(25);
		System.out.println("Total discount is:"+productObject.getDiscount());
	end